# Generated by Django 3.0.3 on 2020-05-01 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hack_title', models.CharField(max_length=200)),
                ('hack_content', models.TextField()),
                ('hack_published', models.DateTimeField(default=datetime.datetime(2020, 5, 1, 12, 41, 52, 636346), verbose_name='date published')),
                ('hack_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
    ]
