# Generated by Django 3.0.3 on 2020-05-01 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200501_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacks',
            name='hack_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 12, 44, 57, 82108), verbose_name='date published'),
        ),
    ]
