# Generated by Django 3.0.3 on 2020-05-03 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200501_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hack_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='HackSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hack_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AlterField(
            model_name='hack',
            name='hack_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 22, 35, 755698), verbose_name='date published'),
        ),
    ]
