# Generated by Django 3.0.3 on 2020-05-04 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200503_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackcategory',
            name='category_photo',
            field=models.ImageField(default='/home/christopher/Documents/python/django-hacksite/mysite/media/lifehacks.jpg', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='hack',
            name='hack_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 16, 27, 59, 332539), verbose_name='date published'),
        ),
    ]
