# Generated by Django 3.0.3 on 2020-05-04 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200504_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='hack_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 19, 53, 37, 175161), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='hackcategory',
            name='category_photo',
            field=models.ImageField(default='/media/lifehacks.jpg', upload_to='gallery'),
        ),
    ]
