# Generated by Django 3.0.3 on 2020-05-05 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200504_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackseries',
            name='series_photo',
            field=models.ImageField(default='/media/lifehacks.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='hack',
            name='hack_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 9, 54, 6, 598800), verbose_name='date published'),
        ),
    ]
