# Generated by Django 3.0.3 on 2020-05-05 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200505_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='hack_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 21, 48, 17, 728675), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='hackcategory',
            name='category_photo',
            field=models.ImageField(default='/media/lifehacks.jpg', upload_to=''),
        ),
    ]
