# Generated by Django 3.0.3 on 2020-05-05 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200505_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='hack_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 21, 55, 15, 839111), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='hackcategory',
            name='category_photo',
            field=models.ImageField(default='/media/lifehacks.jpg', upload_to='media'),
        ),
    ]
