# Generated by Django 2.2.12 on 2020-05-13 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200505_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='hack_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 11, 0, 52, 156878), verbose_name='date published'),
        ),
    ]
