# Generated by Django 2.2.12 on 2020-05-13 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200513_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='hack_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 13, 58, 40, 591598), verbose_name='date published'),
        ),
    ]
